import Head from "next/head";
import { PropsWithChildren } from "react";
// import Footer from "../Marketing/Footer";
import Header from "./Header";

export default function MainLayout({ children }: PropsWithChildren) {
  return (
    <>
      <Head>
        <title>Rumah 123</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col bg-white">
        <Header />
        <div className="mx-auto w-full">{children}</div>
      </main>
    </>
  );
}
